// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PodcastDirectoryAPI.Data;

namespace PodcastDirectoryAPI.Migrations
{
    [DbContext(typeof(PodcastDirectoryAPIContext))]
    partial class PodcastDirectoryAPIContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("PodcastDirectoryAPI.Data.Users", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<int>("PodcastID");

                    b.HasKey("UserID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PodcastDirectoryAPI.Domain.ContactInfo", b =>
                {
                    b.Property<int>("ContactID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FacebookPageURL");

                    b.Property<string>("InstagramHandle");

                    b.Property<int>("PodcastID");

                    b.Property<string>("TwitterPageURL");

                    b.Property<string>("WebsiteURL");

                    b.HasKey("ContactID");

                    b.ToTable("ContactInfos");
                });

            modelBuilder.Entity("PodcastDirectoryAPI.Domain.PodcastDetails", b =>
                {
                    b.Property<int>("PodcastID")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active");

                    b.Property<string>("Category");

                    b.Property<string>("Description");

                    b.Property<string>("LogoPath");

                    b.Property<string>("Name");

                    b.Property<int>("YearLaunched");

                    b.HasKey("PodcastID");

                    b.ToTable("PodcastDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
